### ISSUE TITLE
Allow users to click hyperlinks inside resumes

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#221]

**Comment by fannydengdeng** [comment]
Two things 1) text is not selectable on the PDF when in edit mode (turned off for better user experience for annotations) 2) even if text is selectable the hyperlinks are not guaranteed to be rendered in the same div, as in the text may be split up, due to how it was implemented. Plus the ability to click through to external links from a user uploaded document is potentially dangerous.
