### ISSUE TITLE
Pagination on Resume Pool

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#6]

**Comment by dongyuzheng** [comment]
Make sure you don't make multiple backend calls when you switch pages

**Comment by agapic** [comment]
I haven't really done pagination before (so correct me if I'm wrong) but isn't the purpose of pagination to make a new backend call every time we load a new page (like scroll down). It's just more efficient because instead of loading say 1000 objects, we load 100 each batch.

How do you propose to do it without multiple backend calls?

**Comment by dongyuzheng** [comment]
Yup, what you mentioned is the correct way to do it.
That would involve backend changes too. Do you want to try your hand at gql pagination?
https://gist.github.com/mbrochh/f92594ab8188393bd83c892ef2af25e6

**Comment by agapic** [comment]
Let me read into it a little more tonight so I understand how the flow works end to end (from the React FE to the Python BE).

Where in the BE is an appropriate place to add this?

**Comment by dongyuzheng** [comment]
Around here https://github.com/dongyuzheng/rezq-backend/blob/master/rezq_backend/rezq/api/v1/schemas/resume.py#L103

**Comment by agapic** [comment]
Update: Backend part is complete.
