### ISSUE TITLE
Frontend `make build` warnings

### ISSUE THREAD

**Issue by dongyuzheng** [rezqio/issues#99]
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  bundle.js (2.67 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (2.67 MiB)
      bundle.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

```

**Comment by dongyuzheng** [comment]
https://itnext.io/react-router-and-webpack-v4-code-splitting-using-splitchunksplugin-f0a48f110312

**Comment by evancoa** [comment]
Ya, I tried a bunch of stuff that didn't work out. The way described in almost all tutorials is to use: `optimization: {...}` for the splitchunksplugin, and it doesn't work for our app (possibly because of the way we've set up our webpack config? I tried debugging but couldn't narrow it down).

Basically the issue we get is (other people don't experience this, aside from https://stackoverflow.com/questions/52336624/after-splitting-chunks-in-webpack-unable-to-run-app which didn't help), we get a blank page because not all the chunks are loaded up.

Even after splitting, it's incredibly difficult to make each chunk fit the 244kb limit (you can google this, many many people ignore this issue, as it is making a lot of assumptions about the users environment), and we'll require many more changes such as doing a codebase-wide refactoring to use optimizations such as dynamic loading for routes (which will definitely break the way we pass down some props).

Not sure where to go from here, what do you think?

**Comment by dongyuzheng** [comment]
We should look into what's making our bundle.js so big
